pipeline:
  name: gk-IAC-WILF
  identifier: gkIACWILF
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: IAC
        identifier: IAC
        description: ""
        type: IACM
        spec:
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          workspace: gkworkspacewlif
          execution:
            steps:
              - step:
                  type: Checkov
                  name: Checkov_1
                  identifier: Checkov_1
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                    advanced:
                      log:
                        level: info
              - step:
                  type: IACMTerraformPlugin
                  name: init
                  identifier: init
                  timeout: 10m
                  spec:
                    command: init
              - step:
                  type: IACMTerraformPlugin
                  name: plan
                  identifier: plan
                  timeout: 10m
                  spec:
                    command: plan
              - step:
                  type: IACMTerraformPlugin
                  name: apply
                  identifier: apply
                  timeout: 10m
                  spec:
                    command: apply
          codebase:
            connectorRef: gkgitconnector
            repoName: Terraform
            build: <+input>
        tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gkgitconnector
        repoName: Terraform
        build: <+input>
        sparseCheckout: []
